;Service loader configuration file.

[CONFIG]
;BACKEND
DOMAIN           = 127.0.0.1
BACKEND_PORT     = 8000
;number of seconds in week
SESSION_DURATION = 604800

;CORE
;interval of sending a new request to discord in seconds
REQUEST_INTERVAL = 3

;FRONTEND
FRONTEND_PORT    = 3000
